### ISSUE TITLE
Only partially working in Channels

### ISSUE THREAD

**Issue by mtjoernelund** [edc1591/homebridge-theater-mode#10]
Just installed this and played around with it a little. It seems to do the trick for most videoplayers except the Channels App. 

When starting to watch tv in Channels it will execute a button press for play. But the plugin does not seem to register when playback in Channels are paused or stopped. May be due to the fact that Channels use their own custom player rather than the build-in tvOS player. Going to look around at the output from node-appletv and report back. Any other ideas?

**Comment by evandcoleman** [comment]
The use of a custom player is likely the cause. If this is still causing issues, please open an issue on the `node-appletv` Github repo.
