### ISSUE TITLE
Apple TV Pairing Problem

### ISSUE THREAD

**Issue by Crox77** [edc1591/homebridge-theater-mode#14]
Hi I have been following this Guide to Add Apple TV Theatre Mode to My Homebridge and have been following this Guide https://github.com/edc1591/homebridge-theater-mode/blob/master/README.md

All seems to install fine until I try to Pair the Apple TV 4K Box when I type appletv pair it is then followed by this error message:

/usr/local/lib/node_modules/node-appletv/node_modules/bindings/bindings.js:91
throw err
^

Error: Could not locate the bindings file. Tried:
→ /usr/local/lib/node_modules/node-appletv/node_modules/ed25519/build/ed25519.node
→ /usr/local/lib/node_modules/node-appletv/node_modules/ed25519/build/Debug/ed25519.node
→ /usr/local/lib/node_modules/node-appletv/node_modules/ed25519/build/Release/ed25519.node
→ /usr/local/lib/node_modules/node-appletv/node_modules/ed25519/out/Debug/ed25519.node
→ /usr/local/lib/node_modules/node-appletv/node_modules/ed25519/Debug/ed25519.node
→ /usr/local/lib/node_modules/node-appletv/node_modules/ed25519/out/Release/ed25519.node
→ /usr/local/lib/node_modules/node-appletv/node_modules/ed25519/Release/ed25519.node
→ /usr/local/lib/node_modules/node-appletv/node_modules/ed25519/build/default/ed25519.node
→ /usr/local/lib/node_modules/node-appletv/node_modules/ed25519/compiled/10.15.0/darwin/x64/ed25519.node
at bindings (/usr/local/lib/node_modules/node-appletv/node_modules/bindings/bindings.js:88:9)
at Object. (/usr/local/lib/node_modules/node-appletv/node_modules/ed25519/index.js:1:99)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)

Anybody have any ideas?

As I said I am very new to this and none of that makes sense and I can not find what it means by "Can not find Bindings File"

Thank You
Paul

**Comment by evandcoleman** [comment]
A quick Google search indicates this is a fairly common problem. Try the steps outlined [here](https://github.com/nfarina/homebridge/issues/846#issuecomment-401621399) but replacing `homebridge` with `node-appletv`.

**Comment by Crox77** [comment]
Hi Evan
Thanks for your reply,
I now get this error message when installing

Error: make nodesodium exited with code null
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/node-appletv/node_modules/sodium/install.js:287:19)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 install: `node install.js --install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Crox-iMac/.npm/_logs/2019-01-31T17_08_01_023Z-debug.log

**Comment by Crox77** [comment]
Ok, Finally Installed but still get the same bindings error message

**Comment by Crox77** [comment]
Finally sorted and now working, Thanks

**Comment by bfulham** [comment]
how did you fix it? I think it might solve my problem.
