### ISSUE TITLE
Very slow responses

### ISSUE THREAD

**Issue by crxporter** [edc1591/homebridge-theater-mode#3]
I love the idea behind this program and hope to get it working well with both of my TVs soon. I've got the whole thing up and running on both my macbook and a Debian virtual machine. The first "play" command goes through immediately when I start a movie/show but subsequent play/pause/stop commands are very slow as I watch them in the terminal running homebridge. 

Once the command shows up in homeridge the "button press" and scene is set immediately. Any idea what's slowing the commands coming in? At times it takes like 2 - 3 minutes before recognizing that I've changed the play state. 

Any ideas on how to fix this?

**Comment by crxporter** [comment]
Got an update here - I got out a fresh raspberry pi 3 and loaded up homebridge on there. I seem to be getting much quicker response times - in the 5 to 10 second range now! I don't know what was wrong with the OS x or fresh Debian VM... but the pi looks promising.

Thanks for the great plugin, I look forward to any ways you find to make it even better

**Comment by ptrvg** [comment]
I get very random delays up to a minute with Homebridge running on a pi3 using this plugin.
I found another solution that is almost instant using the homebridge-dacp plugin.
If I understand correctly the latter plugin uses a different protocol to talk to the Apple TV then this one.

**Comment by crxporter** [comment]
Thanks for the tip, ptrvg - the homebridge-dacp is indeed very fast. I think the solution from homebridge-theater-mode is much more "elegant" though... with the switch to turn it on/off and the 3 buttons to change my automation.

I'll keep watching both projects to see what happens.

**Comment by evandcoleman** [comment]
This seems to be an issue with tvOS 11.3 as it's almost instantaneous on earlier versions. Version 1.0.8 of node-applets makes it a little better but I'm currently investigating ways to improve it further. Since this is a node-appletv issue, I'm closing this in favor of [#4](https://github.com/edc1591/node-appletv/issues/4).
