### ISSUE TITLE
Love the idea and it works really great to my home-theater setup.

### ISSUE THREAD

**Issue by Aekung** [edc1591/homebridge-theater-mode#6]
Really love the idea of the plugin and it really works as it should. If only the delay can be fixed or at least be faster, this will be perfect.

Thanks for such a useful plugin.

**Comment by sethfowler** [comment]
It really does rule. Thank you, @edc1591.

**Comment by evandcoleman** [comment]
So happy to hear that! Really glad you're both finding it useful! Dealing with the delay is certainly something I'd like to do. It's been some time since I've worked on this so maybe there's been some updates to the protocol.
