### ISSUE TITLE
Slow Or Not Triggering Events

### ISSUE THREAD

**Issue by AustinRobinson** [edc1591/homebridge-theater-mode#8]
Is there any way I can speed this up and make it more reliable?

**Comment by AustinRobinson** [comment]
When I run 
```bash
appletv --credentials <credentials-from-pairing> state
```

sometimes it will not work and keep printing the same state over and over again but most of the time it works almost flawlessly with having the correct state and under one second delay. I can get this to work in the home app but it's not as fast (up to a full minute if not more.) What I don't understand is why can it be so fast using the the command line interface but not in the "homebridge-theater-mode" plugin. Any help would be appreciated.

**Comment by AustinRobinson** [comment]
I just did some more experimenting and it seems to only work if you enable theater mode while the Apple TV is in either a play or paused state. If you enable theater mode or run 
```bash
appletv --credentials <credentials-from-pairing> state
```
while in a stopped state, it has a lot of delays and most the time, return the incorrect state.

**Comment by evandcoleman** [comment]
I've encountered this a few times in my testing and I'd just attributed it to a flakey new protocol. It's been a while so I may take another stab in the future to see if things have changed.
